### ISSUE TITLE
duplicated entries in shortcuts conf

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt-globalkeys#132]
##### Expected Behavior
each keyboard shortcut should be unique in config

##### Current Behavior
it isn't

##### Possible Solution
fix ti

##### Steps to Reproduce (for bugs)
provide the same key in /usr/share conf. etc/xdg and $HOME/.config - maybe with different numbers

##### Context

![](https://i.imgur.com/Y2PbNjr.png)
^^^ i really don't like it :sunglasses: 

Possible related to: https://github.com/lxqt/lxqt-globalkeys/issues/125

Imho the command/key combination should be unique, i have nothing against 

ctrl a and ctrl b doing the same thing - might be legit, but i don't want to see

11 ctrl a action foo
12 crtl a action foo
13 crtl a action foo

##### System Information
latest git

**Comment by tsujan** [comment]
I agree. The method used by LXQt didn't feel "natural" to me from start but it worked fine.

There are things we could learn from KDE -- at least, it could be inspiring -- but I'm afraid a backward compatible fix may not be possible in this case.

**Comment by agaida** [comment]
In this special case i really don't care about backward compat - and the to some extend we can be "backward-compatible" - read a current configuration and take the first valid entry for a key - drop all others. Done :smile:

**Comment by tsujan** [comment]
Yes, in addition to a new way of storing shortcuts, some code is needed to translate the old format to the new one.

**Comment by tsujan** [comment]
Was it inherited from razor-Qt?

**Comment by agaida** [comment]
no clue, i guess so

**Comment by tsujan** [comment]
OK, KDE's method isn't so inspirational ;)

```
[Data_5_1]
Comment=Comment
Enabled=true
Name=FeatherPad
Type=SIMPLE_ACTION_DATA

[Data_5_1Actions]
ActionsCount=1

[Data_5_1Actions0]
CommandURL=featherpad
Type=COMMAND_URL

[Data_5_1Conditions]
Comment=
ConditionsCount=0

[Data_5_1Triggers]
Comment=Simple_action
TriggersCount=1

[Data_5_1Triggers0]
Key=Meta+F
Type=SHORTCUT
Uuid={b8ad549f-39a6-49ee-a584-7ba3ec5130ae}
```

Int our method, shortcuts are section names. So far so good. It seems that `.1`, `.2`, `.3`,... are put there to support empty shortcuts but they defeat the purpose of choosing shortcuts as section names because they aren't unique anymore and can result in what's described in this report.

I think If, somehow, we remove `.1`, `.2`, `.3`,.. when shortcuts aren't empty, the problem should be solved because there couldn't be 2 section with identical names.

**Comment by tsujan** [comment]
Another method:

Use numbers as section names, put shortcuts inside sections, and *add code to search for ambiguous shortcuts*: either prevent them or show a warning. An example:
```
[56]
Comment=FeatherPad
Enabled=true
Exec=featherpad
Shortcut=Meta+F
```

**Comment by tsujan** [comment]
I assigned it to myself because I've dealt with shortcut ambiguity in other apps but it won't be for 0.15. If someone can make it efficient before 0.15, please do so!

**Comment by agaida** [comment]
Will result in a funny sorting ...

**Comment by tsujan** [comment]
Sorting won't change in the GUI.

**Comment by tsujan** [comment]
Please see if https://github.com/lxqt/lxqt-globalkeys/commit/794c7807c34818397f1e2f3a7a9bcf723f518cfd fixes your problem and is worth making a PR.

As for `.1`, `.2`,..., they're needed by the current code because the code allows a key sequence to be repeated but decides which one should be activated.

**Comment by tsujan** [comment]
In other words, the current code efficiently deals with ambiguity (although in a way that I don't like).

**Comment by agaida** [comment]
Meh - ok, i was a longterm database guy - and if anyone had introduced any kind of not needed sequenz number i had yelled at him long and loud - the point ambiguity can be simply handled by the triplet {$key, $command/action, $activation-state} - not more, not less.

**Comment by tsujan** [comment]
> the point 'ambiguity' can be simply handled by the triplet {$key, $command/action, $activation-state} - not more, not less.

If there was only one way of doing each job, we would have only one OS and one program of each kind.

Loading *identical* shortcuts was a problem that can be fixed by the proposed patch but showing ambiguous ones while enabling only one of them is a feature — although I may not like it. It needs those numbers after dots.

Config files aren't for manual editing. Most of them can be edited but they're created by apps and can contain elements whose meanings aren't obvious to users. The presence of something like ♥ in a config file isn't a problem, let alone dots followed by numbers.

**Comment by agaida** [comment]
:)

**Comment by agaida** [comment]
Anyways, works like charm - and that's all what count - and i just discovered a new github thing that i like - never noticed it before:
![](https://i.imgur.com/AZ5rt0U.png)

**Comment by tsujan** [comment]
Wasn't it there before? I don't remember.

**Comment by agaida** [comment]
no, never seen a branch overview which make it possible
* to create a PR directly
* delete branches 
* shows the differences in a short way
* and shows meanwhile closed, but mentioned bugs

Really useful i think

**Comment by agaida** [comment]
done
